import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const pt = {
  translation: {
    brand: 'hermes', backoffice: 'BACKOFFICE', dashboard: 'Visão geral', tenants: 'Tenants', plans: 'Planos', users: 'Usuários', settings: 'Minha conta', logout: 'Sair', adminEyebrow: 'GESTÃO MULTITENANT', adminHeadline: 'Controle claro. Operação segura.', adminIntro: 'Tenants, planos e acessos em um só lugar.',
    loginTitle: 'Acesse o backoffice', loginHint: 'Use suas credenciais para continuar.', email: 'E-mail', password: 'Senha', signIn: 'Entrar', signingIn: 'Entrando…', invalidLogin: 'Não foi possível entrar. Verifique suas credenciais.',
    welcome: 'Olá, {{name}}', sysSummary: 'Acompanhe a operação de todos os tenants.', ownerSummary: 'Gerencie sua organização e seus acessos.', activeTenants: 'Tenants cadastrados', activeUsers: 'Usuários ativos', availablePlans: 'Planos disponíveis', controlCenter: 'HERMES CONTROL CENTER', sysPanelTitle: 'Sua operação, sem pontos cegos.', ownerPanelTitle: 'Tudo certo por aqui.', sysPanelText: 'Use o menu para administrar organizações, assinaturas e acessos com isolamento por tenant.', ownerPanelText: 'Atualize os dados da sua organização e mantenha os acessos da equipe em dia.',
    newTenant: 'Novo tenant', editTenant: 'Editar tenant', newPlan: 'Novo plano', editPlan: 'Editar plano', newUser: 'Novo usuário', editUser: 'Editar usuário', search: 'Buscar…', actions: 'Ações', edit: 'Editar', deactivate: 'Desativar', reactivate: 'Reativar', delete: 'Excluir', cancel: 'Cancelar', save: 'Salvar', saving: 'Salvando…', confirm: 'Confirmar', refresh: 'Atualizar', noResults: 'Nenhum registro encontrado.',
    businessName: 'Nome empresarial', companyName: 'Nome fantasia', taxId: 'CNPJ / documento fiscal', phone: 'Telefone', website: 'Site', address: 'Endereço', address2: 'Complemento', city: 'Cidade', province: 'Estado', postalCode: 'CEP', graceDays: 'Dias de carência',
    name: 'Nome', role: 'Perfil', tenant: 'Tenant', status: 'Status', active: 'Ativo', inactive: 'Inativo', temporaryPassword: 'Senha temporária', firstLogin: 'Troca obrigatória no primeiro acesso', global: 'Global',
    planName: 'Nome do plano', basePrice: 'Preço base', includedUsers: 'Usuários incluídos', periodDays: 'Período (dias)', paymentDate: 'Data de cobrança', aiQuota: 'Cota diária de IA', tiers: 'Faixas adicionais', addTier: 'Adicionar faixa', upToUsers: 'Até usuários (0 = sem limite)', pricePerUser: 'Preço por usuário', subscription: 'Assinatura', manageSubscription: 'Gerenciar assinatura', noSubscription: 'Nenhuma assinatura ativa.',
    changePassword: 'Alterar senha', currentPassword: 'Senha atual', newPassword: 'Nova senha', confirmPassword: 'Confirmar nova senha', passwordChanged: 'Senha alterada com sucesso.', firstLoginTitle: 'Crie sua senha definitiva', firstLoginHint: 'Por segurança, substitua a senha temporária antes de continuar.', passwordMin: 'A senha deve ter ao menos 8 caracteres.', passwordMismatch: 'As senhas não coincidem.',
    deletePlanTitle: 'Excluir plano?', deletePlanText: 'A exclusão é permanente e só será concluída se nenhum tenant estiver usando este plano.', deactivateTitle: 'Alterar acesso?', deactivateText: 'O usuário perderá o acesso imediatamente.', selfDeactivate: 'Você não pode desativar a própria conta.', forbidden: 'Você não tem acesso a esta página.', genericError: 'Não foi possível concluir a operação.', loading: 'Carregando…', menu: 'Abrir menu', close: 'Fechar', language: 'Idioma',
  },
}

const en = {
  translation: {
    brand: 'hermes', backoffice: 'BACKOFFICE', dashboard: 'Overview', tenants: 'Tenants', plans: 'Plans', users: 'Users', settings: 'My account', logout: 'Sign out', adminEyebrow: 'MULTITENANT MANAGEMENT', adminHeadline: 'Clear control. Secure operations.', adminIntro: 'Tenants, plans, and access in one place.',
    loginTitle: 'Sign in to the backoffice', loginHint: 'Use your credentials to continue.', email: 'Email', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in…', invalidLogin: 'Could not sign in. Check your credentials.',
    welcome: 'Hello, {{name}}', sysSummary: 'Monitor operations across every tenant.', ownerSummary: 'Manage your organization and access.', activeTenants: 'Registered tenants', activeUsers: 'Active users', availablePlans: 'Available plans', controlCenter: 'HERMES CONTROL CENTER', sysPanelTitle: 'Your operation, without blind spots.', ownerPanelTitle: 'Everything looks good.', sysPanelText: 'Use the menu to manage organizations, subscriptions, and access with tenant isolation.', ownerPanelText: 'Keep your organization details and team access up to date.',
    newTenant: 'New tenant', editTenant: 'Edit tenant', newPlan: 'New plan', editPlan: 'Edit plan', newUser: 'New user', editUser: 'Edit user', search: 'Search…', actions: 'Actions', edit: 'Edit', deactivate: 'Deactivate', reactivate: 'Reactivate', delete: 'Delete', cancel: 'Cancel', save: 'Save', saving: 'Saving…', confirm: 'Confirm', refresh: 'Refresh', noResults: 'No records found.',
    businessName: 'Legal name', companyName: 'Trading name', taxId: 'Tax ID', phone: 'Phone', website: 'Website', address: 'Address', address2: 'Address line 2', city: 'City', province: 'State', postalCode: 'Postal code', graceDays: 'Grace period days',
    name: 'Name', role: 'Role', tenant: 'Tenant', status: 'Status', active: 'Active', inactive: 'Inactive', temporaryPassword: 'Temporary password', firstLogin: 'Require password change on first sign-in', global: 'Global',
    planName: 'Plan name', basePrice: 'Base price', includedUsers: 'Included users', periodDays: 'Period (days)', paymentDate: 'Billing date', aiQuota: 'Daily AI quota', tiers: 'Additional tiers', addTier: 'Add tier', upToUsers: 'Up to users (0 = unlimited)', pricePerUser: 'Price per user', subscription: 'Subscription', manageSubscription: 'Manage subscription', noSubscription: 'No active subscription.',
    changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', passwordChanged: 'Password changed successfully.', firstLoginTitle: 'Create your permanent password', firstLoginHint: 'For security, replace the temporary password before continuing.', passwordMin: 'The password must contain at least 8 characters.', passwordMismatch: 'The passwords do not match.',
    deletePlanTitle: 'Delete plan?', deletePlanText: 'Deletion is permanent and succeeds only when no tenant is using this plan.', deactivateTitle: 'Change access?', deactivateText: 'The user will lose access immediately.', selfDeactivate: 'You cannot deactivate your own account.', forbidden: 'You do not have access to this page.', genericError: 'The operation could not be completed.', loading: 'Loading…', menu: 'Open menu', close: 'Close', language: 'Language',
  },
}

i18n.use(LanguageDetector).use(initReactI18next).init({ resources: { 'pt-BR': pt, en }, fallbackLng: 'pt-BR', interpolation: { escapeValue: false }, detection: { order: ['localStorage', 'navigator'], caches: ['localStorage'] } })
export default i18n
