import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Building2, CheckCircle2, CircleOff, CreditCard, Pencil, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { useDispatch, useSelector } from 'react-redux'
import { useTranslation } from 'react-i18next'
import { api, apiMessage } from '../api'
import type { AppDispatch, RootState } from '../store'
import { loadCities, loadPlans, loadProvinces, loadTenantPlan, loadTenants, loadUsers } from '../store'
import type { BusinessPlan, BusinessPlanTier, Tenant, TenantPlan, User } from '../types'
import { Confirm, Empty, Form, Loading, Modal, PageHeader, SearchBox } from '../components/UI'

const money = (cents: number, locale: string) => new Intl.NumberFormat(locale, { style: 'currency', currency: 'BRL' }).format(cents / 100)
const today = () => new Date().toISOString().slice(0, 10)

const blankTenant: Tenant = { businessName: '', companyName: '', taxId: '', email: '', phone: '', website: '', addressLine1: '', addressLine2: '', locality: '', administrativeArea: '', postalCode: '', countryCode: 'BR', paymentGraceDays: 0 }
export function TenantsPage() {
  const { t } = useTranslation(); const dispatch = useDispatch<AppDispatch>(); const { tenants, plans, provinces, cities, tenantPlans, loading } = useSelector((s: RootState) => s.data); const session = useSelector((s: RootState) => s.auth.session)!
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<Tenant | null>(null); const [subscription, setSubscription] = useState<Tenant | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { dispatch(loadTenants()); dispatch(loadProvinces()); if (session.role === 'SysAdmin') dispatch(loadPlans()) }, [dispatch, session.role])
  useEffect(() => { const province = provinces.find((item) => item.acronym === editing?.administrativeArea); if (province) dispatch(loadCities(province.id)) }, [dispatch, editing?.administrativeArea, provinces])
  const filtered = tenants.filter((x) => `${x.businessName} ${x.companyName} ${x.taxId} ${x.email}`.toLowerCase().includes(search.toLowerCase()))
  const save = async (e: FormEvent) => { e.preventDefault(); if (!editing) return; setSaving(true); setError(''); try { if (editing.id) await api.put(`/tenant/${editing.id}`, editing); else await api.post('/tenant', editing); setEditing(null); dispatch(loadTenants()) } catch (err) { setError(apiMessage(err, t('genericError'))) } finally { setSaving(false) } }
  const openPlan = (tenant: Tenant) => { if (!tenant.id) return; setSubscription(tenant); dispatch(loadTenantPlan(tenant.id)) }
  return <><PageHeader title={t('tenants')} subtitle={session.role === 'SysAdmin' ? t('sysSummary') : t('ownerSummary')} actions={<><button className="btn secondary" onClick={() => dispatch(loadTenants())}><RefreshCw size={16} />{t('refresh')}</button>{session.role === 'SysAdmin' && <button className="btn primary" onClick={() => setEditing({ ...blankTenant })}><Plus size={17} />{t('newTenant')}</button>}</>} /><div className="toolbar"><SearchBox value={search} onChange={setSearch} /></div>{loading && !tenants.length ? <Loading /> : !filtered.length ? <Empty /> : <div className="tenant-grid">{filtered.map((tenant) => <article className="tenant-card" key={tenant.id}><div className="tenant-card-head"><span><Building2 /></span><small>#{tenant.id}</small></div><h3>{tenant.companyName || tenant.businessName}</h3><p>{tenant.businessName}</p><dl><div><dt>{t('taxId')}</dt><dd>{tenant.taxId}</dd></div><div><dt>{t('email')}</dt><dd>{tenant.email || '—'}</dd></div><div><dt>{t('city')}</dt><dd>{[tenant.locality, tenant.administrativeArea].filter(Boolean).join(' · ') || '—'}</dd></div></dl><footer><button onClick={() => setEditing({ ...tenant })}><Pencil size={15} />{t('edit')}</button>{session.role === 'SysAdmin' && <button onClick={() => openPlan(tenant)}><CreditCard size={15} />{t('subscription')}</button>}</footer></article>)}</div>}
    {editing && <Modal title={editing.id ? t('editTenant') : t('newTenant')} onClose={() => setEditing(null)} wide><Form onSubmit={save} error={error} saving={saving}><label>{t('businessName')}<input required value={editing.businessName} onChange={(e) => setEditing({ ...editing, businessName: e.target.value })} /></label><label>{t('companyName')}<input required value={editing.companyName || ''} onChange={(e) => setEditing({ ...editing, companyName: e.target.value })} /></label><label>{t('taxId')}<input required value={editing.taxId} onChange={(e) => setEditing({ ...editing, taxId: e.target.value })} /></label><label>{t('email')}<input type="email" value={editing.email || ''} onChange={(e) => setEditing({ ...editing, email: e.target.value })} /></label><label>{t('phone')}<input value={editing.phone || ''} onChange={(e) => setEditing({ ...editing, phone: e.target.value })} /></label><label>{t('website')}<input type="url" value={editing.website || ''} onChange={(e) => setEditing({ ...editing, website: e.target.value })} /></label><label className="span-2">{t('address')}<input value={editing.addressLine1 || ''} onChange={(e) => setEditing({ ...editing, addressLine1: e.target.value })} /></label><label>{t('address2')}<input value={editing.addressLine2 || ''} onChange={(e) => setEditing({ ...editing, addressLine2: e.target.value })} /></label><label>{t('province')}<select value={editing.administrativeArea || ''} onChange={(e) => { const province = provinces.find((item) => item.acronym === e.target.value); setEditing({ ...editing, administrativeArea: e.target.value, locality: '' }); if (province) dispatch(loadCities(province.id)) }}><option value="">—</option>{provinces.map((province) => <option key={province.id} value={province.acronym}>{province.name}</option>)}</select></label><label>{t('city')}<select value={editing.locality || ''} onChange={(e) => setEditing({ ...editing, locality: e.target.value })}><option value="">—</option>{cities.map((city) => <option key={city.id} value={city.name}>{city.name}</option>)}</select></label><label>{t('postalCode')}<input value={editing.postalCode || ''} onChange={(e) => setEditing({ ...editing, postalCode: e.target.value })} /></label><label>{t('graceDays')}<input type="number" min="0" value={editing.paymentGraceDays || 0} onChange={(e) => setEditing({ ...editing, paymentGraceDays: Number(e.target.value) })} /></label></Form></Modal>}
    {subscription?.id && <SubscriptionModal tenant={subscription} plans={plans} value={tenantPlans[subscription.id]} onClose={() => setSubscription(null)} onSaved={() => { dispatch(loadTenantPlan(subscription.id!)); setSubscription(null) }} />}
  </>
}

function SubscriptionModal({ tenant, plans, value, onClose, onSaved }: { tenant: Tenant; plans: BusinessPlan[]; value?: TenantPlan | null; onClose: () => void; onSaved: () => void }) {
  const { t } = useTranslation(); const [form, setForm] = useState<TenantPlan>({ id: value?.id, uuid: value?.uuid, tenantId: tenant.id!, businessPlanId: value?.businessPlanId || plans[0]?.id || 0, paymentDate: value?.paymentDate || today(), active: true }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (value) setForm(value) }, [value])
  const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); try { await api.post(`/tenant/${tenant.id}/plan`, form); onSaved() } catch (err) { setError(apiMessage(err, t('genericError'))) } finally { setSaving(false) } }
  return <Modal title={`${t('subscription')} · ${tenant.companyName || tenant.businessName}`} onClose={onClose}><Form onSubmit={submit} error={error} saving={saving}><label className="span-2">{t('plans')}<select value={form.businessPlanId} onChange={(e) => setForm({ ...form, businessPlanId: Number(e.target.value) })}>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {money(plan.priceInCents, 'pt-BR')}</option>)}</select></label><label className="span-2">{t('paymentDate')}<input type="date" required value={form.paymentDate} onChange={(e) => setForm({ ...form, paymentDate: e.target.value })} /></label></Form></Modal>
}

const blankPlan: BusinessPlan = { name: '', priceInCents: 0, availableUsers: 1, periodDays: 30, paymentDate: today(), dailyAiQuota: 4, tiers: [] }
export function PlansPage() {
  const { t, i18n } = useTranslation(); const dispatch = useDispatch<AppDispatch>(); const { plans, loading } = useSelector((s: RootState) => s.data); const [search, setSearch] = useState(''); const [editing, setEditing] = useState<BusinessPlan | null>(null); const [removing, setRemoving] = useState<BusinessPlan | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { dispatch(loadPlans()) }, [dispatch]); const filtered = plans.filter((p) => p.name.toLowerCase().includes(search.toLowerCase()))
  const save = async (e: FormEvent) => { e.preventDefault(); if (!editing) return; setSaving(true); setError(''); try { if (editing.id) await api.put(`/business-plan/${editing.id}`, editing); else await api.post('/business-plan', editing); setEditing(null); dispatch(loadPlans()) } catch (err) { setError(apiMessage(err, t('genericError'))) } finally { setSaving(false) } }
  const remove = async () => { if (!removing?.id) return; try { await api.delete(`/business-plan/${removing.id}`); setRemoving(null); dispatch(loadPlans()) } catch (err) { setError(apiMessage(err, t('genericError'))); setRemoving(null) } }
  return <><PageHeader title={t('plans')} actions={<><button className="btn secondary" onClick={() => dispatch(loadPlans())}><RefreshCw size={16} />{t('refresh')}</button><button className="btn primary" onClick={() => setEditing({ ...blankPlan })}><Plus size={17} />{t('newPlan')}</button></>} /><div className="toolbar"><SearchBox value={search} onChange={setSearch} />{error && <span className="inline-error">{error}</span>}</div>{loading && !plans.length ? <Loading /> : !filtered.length ? <Empty /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>{t('planName')}</th><th>{t('basePrice')}</th><th>{t('includedUsers')}</th><th>{t('periodDays')}</th><th>{t('aiQuota')}</th><th>{t('actions')}</th></tr></thead><tbody>{filtered.map((plan) => <tr key={plan.id}><td><b>{plan.name}</b><small>{plan.tiers.length} {t('tiers').toLowerCase()}</small></td><td>{money(plan.priceInCents, i18n.language)}</td><td>{plan.availableUsers}</td><td>{plan.periodDays}</td><td>{plan.dailyAiQuota}</td><td><div className="row-actions"><button onClick={() => setEditing(structuredClone(plan))}><Pencil size={16} /></button><button className="danger-text" onClick={() => setRemoving(plan)}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div></div>}
    {editing && <Modal title={editing.id ? t('editPlan') : t('newPlan')} onClose={() => setEditing(null)} wide><Form onSubmit={save} error={error} saving={saving}><label className="span-2">{t('planName')}<input required value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><label>{t('basePrice')}<input type="number" min="0" step="1" value={editing.priceInCents} onChange={(e) => setEditing({ ...editing, priceInCents: Number(e.target.value) })} /></label><label>{t('includedUsers')}<input type="number" min="1" value={editing.availableUsers} onChange={(e) => setEditing({ ...editing, availableUsers: Number(e.target.value) })} /></label><label>{t('periodDays')}<input type="number" min="1" value={editing.periodDays} onChange={(e) => setEditing({ ...editing, periodDays: Number(e.target.value) })} /></label><label>{t('paymentDate')}<input type="date" value={editing.paymentDate} onChange={(e) => setEditing({ ...editing, paymentDate: e.target.value })} /></label><label>{t('aiQuota')}<input type="number" min="1" value={editing.dailyAiQuota} onChange={(e) => setEditing({ ...editing, dailyAiQuota: Number(e.target.value) })} /></label><div className="span-2 tier-editor"><div className="tier-title"><b>{t('tiers')}</b><button type="button" className="btn tertiary" onClick={() => setEditing({ ...editing, tiers: [...editing.tiers, { upToUsers: 0, pricePerUserInCents: 0 }] })}><Plus size={15} />{t('addTier')}</button></div>{editing.tiers.map((tier: BusinessPlanTier, index: number) => <div className="tier-row" key={tier.id ?? index}><label>{t('upToUsers')}<input type="number" min="0" value={tier.upToUsers} onChange={(e) => { const tiers = [...editing.tiers]; tiers[index] = { ...tier, upToUsers: Number(e.target.value) }; setEditing({ ...editing, tiers }) }} /></label><label>{t('pricePerUser')}<input type="number" min="0" value={tier.pricePerUserInCents} onChange={(e) => { const tiers = [...editing.tiers]; tiers[index] = { ...tier, pricePerUserInCents: Number(e.target.value) }; setEditing({ ...editing, tiers }) }} /></label><button type="button" onClick={() => setEditing({ ...editing, tiers: editing.tiers.filter((_, i) => i !== index) })}><Trash2 size={16} /></button></div>)}</div></Form></Modal>}
    {removing && <Confirm title={t('deletePlanTitle')} text={t('deletePlanText')} onCancel={() => setRemoving(null)} onConfirm={remove} />}
  </>
}

export function UsersPage() {
  const { t } = useTranslation(); const dispatch = useDispatch<AppDispatch>(); const { users, tenants, loading } = useSelector((s: RootState) => s.data); const session = useSelector((s: RootState) => s.auth.session)!; const [search, setSearch] = useState(''); const [editing, setEditing] = useState<User | null>(null); const [confirming, setConfirming] = useState<User | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { dispatch(loadUsers()); dispatch(loadTenants()) }, [dispatch]); const filtered = useMemo(() => users.filter((u) => `${u.name} ${u.email}`.toLowerCase().includes(search.toLowerCase())), [users, search]); const tenantName = (id?: number | null) => tenants.find((x) => x.id === id)?.companyName || tenants.find((x) => x.id === id)?.businessName || t('global')
  const blank: User = { name: '', email: '', password: '', enabled: true, firstLogin: true, role: 'TenantOwner', tenantId: session.role === 'TenantOwner' ? session.tenantId : tenants[0]?.id }
  const save = async (e: FormEvent) => { e.preventDefault(); if (!editing) return; setSaving(true); setError(''); const payload = { ...editing }; if (!payload.password) delete payload.password; try { if (editing.id) await api.put(`/user/${editing.id}`, payload); else await api.post('/user', payload); setEditing(null); dispatch(loadUsers()) } catch (err) { setError(apiMessage(err, t('genericError'))) } finally { setSaving(false) } }
  const toggle = async () => { if (!confirming?.id) return; if (confirming.id === session.userId) { setError(t('selfDeactivate')); setConfirming(null); return } try { await api.put(`/user/${confirming.id}`, { ...confirming, password: undefined, enabled: !confirming.enabled }); setConfirming(null); dispatch(loadUsers()) } catch (err) { setError(apiMessage(err, t('genericError'))) } }
  return <><PageHeader title={t('users')} actions={<><button className="btn secondary" onClick={() => dispatch(loadUsers())}><RefreshCw size={16} />{t('refresh')}</button><button className="btn primary" onClick={() => setEditing(blank)}><Plus size={17} />{t('newUser')}</button></>} /><div className="toolbar"><SearchBox value={search} onChange={setSearch} />{error && <span className="inline-error">{error}</span>}</div>{loading && !users.length ? <Loading /> : !filtered.length ? <Empty /> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>{t('name')}</th><th>{t('role')}</th><th>{t('tenant')}</th><th>{t('status')}</th><th>{t('actions')}</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id}><td><b>{user.name || '—'}</b><small>{user.email}</small></td><td><span className="badge blue">{user.role}</span></td><td>{tenantName(user.tenantId)}</td><td><span className={`badge ${user.enabled ? 'green' : 'gray'}`}>{user.enabled ? <CheckCircle2 size={13} /> : <CircleOff size={13} />}{user.enabled ? t('active') : t('inactive')}</span></td><td><div className="row-actions"><button onClick={() => setEditing({ ...user, password: '' })}><Pencil size={16} /></button><button className={user.enabled ? 'danger-text' : 'success-text'} disabled={user.id === session.userId} onClick={() => setConfirming(user)}>{user.enabled ? <CircleOff size={16} /> : <CheckCircle2 size={16} />}</button></div></td></tr>)}</tbody></table></div></div>}
    {editing && <Modal title={editing.id ? t('editUser') : t('newUser')} onClose={() => setEditing(null)}><Form onSubmit={save} error={error} saving={saving}><label className="span-2">{t('name')}<input required value={editing.name || ''} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><label className="span-2">{t('email')}<input type="email" required value={editing.email} onChange={(e) => setEditing({ ...editing, email: e.target.value })} /></label><label className="span-2">{editing.id ? t('newPassword') : t('temporaryPassword')}<input type="password" required={!editing.id} value={editing.password || ''} onChange={(e) => setEditing({ ...editing, password: e.target.value })} /></label>{session.role === 'SysAdmin' && <><label>{t('role')}<select value={editing.role} onChange={(e) => setEditing({ ...editing, role: e.target.value as User['role'], tenantId: e.target.value === 'SysAdmin' ? null : editing.tenantId || tenants[0]?.id })}><option value="TenantOwner">TenantOwner</option><option value="SysAdmin">SysAdmin</option></select></label><label>{t('tenant')}<select disabled={editing.role === 'SysAdmin'} value={editing.tenantId || ''} onChange={(e) => setEditing({ ...editing, tenantId: Number(e.target.value) })}>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.companyName || tenant.businessName}</option>)}</select></label></>}<label className="checkbox span-2"><input type="checkbox" checked={editing.enabled} onChange={(e) => setEditing({ ...editing, enabled: e.target.checked })} />{t('active')}</label></Form></Modal>}
    {confirming && <Confirm title={t('deactivateTitle')} text={t('deactivateText')} onCancel={() => setConfirming(null)} onConfirm={toggle} />}
  </>
}
