[package]
name = "business"
version = "0.1.0"
edition = "2024"

[dependencies]
entity = { path = "../entity" }

serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
utoipa = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }

argon2 = "0.6.0"
hex = "0.4.3"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
log = "0.4.34"
sha2 = "0.11.0"


[dependencies.sea-orm]
version = "2.0.3"
features = ["debug-print", "runtime-tokio-native-tls", "sqlx-mysql"]

[features]
mock = ["sea-orm/mock"]

[[test]]
name = "mock"
required-features = ["mock"]
